// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TransactionEnder is an autogenerated mock type for the TransactionEnder type
type TransactionEnder struct {
	mock.Mock
}

// End provides a mock function with given fields: err
func (_m *TransactionEnder) End(err error) error {
	ret := _m.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for End")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionEnder creates a new instance of TransactionEnder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionEnder(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionEnder {
	mock := &TransactionEnder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
