version: '3.8'

services:
  loanflow-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loanflow-app
    restart: always
    environment:
      PGUSER: root
      PGPASSWORD: root
      PGDB: loan-flow
      PGPORT: 5432
      PGHOST: postgres-container
      PGSSL: disable
    ports:
      - "8000:8000"
    networks:
      - loanflow_network

networks:
  loanflow_network:
    external: true
